# Kickstart container config file - see https://gitub.com/c7lab/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "continue/kickstart-flavor-gaia"

command:
  init:
    - "composer update"
